apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleTargetRef: #this refernces the replicaset within the replicaset.yaml
    kind: ReplicaSet
    name: frontend
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
